name: Build and Test

on: 
  push:
    branches:
      - trunk

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setting Up Go 
        uses: actions/setup-go@v4
        with:
          go-version: '^1.19.9'
          check-latest: true
          cache-dependency-path: hello/go.sum
      - name: Running Test
        run: |
          cd hello
          go test -v .

  debug-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setting Up Go 
        uses: actions/setup-go@v4
        with:
          go-version: '^1.19.9'
          check-latest: true
          cache-dependency-path: hello/go.sum
      - name: Building Debug Version
        run: |
          cd hello
          go build -o hello.debug

  prod-build:
    needs:
      - debug-build
      - test
    runs-on: ubuntu-latest
    container:
      image: almalinux:9
    steps:
      - name: Install go toolset 
        run: dnf install -y go-toolset
      - name: Checkout Repository 
        uses: actions/checkout@v3
      - name: Building
        run: |
          cd hello 
          go build -ldflags="-linkmode=external -w -s" -o hello

  package:
    needs:
      - prod-build 
    runs-on: ubuntu-latest 
    container:
      image: almalinux:9
    steps:
      - name: Install go toolset and rpmdevbuild 
        run: dnf install -y go-toolset rpmdevtools
      - name: Checkout Repository 
        uses: actions/checkout@v3
      - name: Setting Up RPM Dev Tools
        run: |
          rpmdev-setuptree
          cp ./SPECS/hello.spec $HOME/rpmbuild/SPECS/

      - name: Packaging Source 
        run: |
          set -e

          VERSION="0.1.1" # Will be changed later
          NAME=hello 

          FULLNAME="$NAME-$VERSION"
          ARCHIVE_NAME=$FULLNAME.tar.xz

          echo "Bundling $ARCHIVE_NAME..."

          rm -rf /tmp/$FULLNAME && cp -r hello /tmp/$FULLNAME

          tar -cvf - -C /tmp $FULLNAME | xz > $ARCHIVE_NAME
          cp $ARCHIVE_NAME $HOME/rpmbuild/SOURCES/

          echo "Cleaning up temp.."

          rm -rf /tmp/$FULLNAME

          echo "Done."


      - name: Building RPM
        run: |
          rpmbuild -ba $HOME/rpmbuild/SPECS/hello.spec

      - name: Listing Artifacts
        run: |
          echo $HOME
          ls -la $HOME/rpmbuild/ && ls -la $HOME/rpmbuild/RPMS/ && ls -la $HOME/rpmbuild/RPMS/x86_64/



